// <auto-generated />
using System;
using DotnetProjectApi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dotnetProject.Migrations
{
    [DbContext(typeof(DotnetProjectDbContext))]
    partial class DotnetProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotnetProjectApi.API.Features.Products.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Sold")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b81a292-901f-42a3-b142-1ee1420292bc"),
                            Description = "Product 1 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Product 1",
                            Price = 10.00m,
                            Sold = 0,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("37e7e501-e02e-4d41-8b2f-d5319bfc4e7a"),
                            Description = "Product 2 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Product 2",
                            Price = 20.00m,
                            Sold = 0,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("2750094b-5162-47fa-8929-d02a0568d208"),
                            Description = "Product 3 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Product 3",
                            Price = 30.00m,
                            Sold = 0,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
